export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";
export const SET_AUTH_SUCCESS = "SET_AUTH_SUCCESS";
export const GET_AUTH_SUCCESS = "GET_AUTH_SUCCESS";
